[build]
  command = "hugo --gc --minify"
#  base    = "exampleSite"
  publish = "public"

[build.environment]
  HUGO_THEME = "hugo-academic"
  HUGO_VERSION = "0.87.0"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.87.0" # if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
    HUGO_VERSION = "0.87.0"
